{{- $ns := default "ravendb" .Values.ravendb.namespace }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ravendb-node
  namespace: {{ $ns }}
  labels:
    {{- include "ravendb-operator.labels" . | nindent 4 }}
