apiVersion: v1
kind: ServiceAccount
metadata:
  name: ravendb-ops-sa
  namespace: ravendb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ravendb-ops
  namespace: ravendb
rules:
  - apiGroups: ["ravendb.ravendb.io"]
    resources: ["ravendbclusters"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ravendb-ops-role-binding
  namespace: ravendb
subjects:
  - kind: ServiceAccount
    name: ravendb-ops-sa
    namespace: ravendb
roleRef:
  kind: Role
  name: ravendb-ops
  apiGroup: rbac.authorization.k8s.io
