apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ravendb-node-renewal-binding
  namespace: ravendb
subjects:
  - kind: ServiceAccount
    name: ravendb-node
    namespace: ravendb
roleRef:
  kind: Role
  name: ravendb-node-renewal
  apiGroup: rbac.authorization.k8s.io
