# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ravendbclusters.ravendb.ravendb.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: Cg==
      service:
        namespace: system   # prefixed by config/default/kustomization.yaml   
        name: webhook-service
        path: /convert
