apiVersion: ravendb.ravendb.io/v1alpha1
kind: RavenDBCluster
metadata:
  labels:
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/managed-by: kustomize
  name: ravendbcluster-sample
  namespace: ravendb
spec:
  nodes:
    - name: a
      publicServerUrl: https://a.thegoldenplatypus.development.run:443
      publicServerUrlTcp: tcp://a-tcp.thegoldenplatypus.development.run:443
      certsSecretRef: ravendb-certs-a
    - name: b
      publicServerUrl: https://b.thegoldenplatypus.development.run:443
      publicServerUrlTcp: tcp://b-tcp.thegoldenplatypus.development.run:443
      certsSecretRef: ravendb-certs-b
    - name: c
      publicServerUrl: https://c.thegoldenplatypus.development.run:443
      publicServerUrlTcp: tcp://c-tcp.thegoldenplatypus.development.run:443
      certsSecretRef: ravendb-certs-c

  image: ravendb/ravendb:latest
  imagePullPolicy: IfNotPresent
  mode: LetsEncrypt
  email: omer.ratsaby@ravendb.net
  license: ''
  domain: thegoldenplatypus.development.run
  serverUrl: https://0.0.0.0:443
  serverUrlTcp: tcp://0.0.0.0:38888
  storageSize: 5Gi
  ingressClassName: nginx

# apiVersion: ravendb.ravendb.io/v1alpha1
# kind: RavenDBCluster
# metadata:
#   labels:
#     app.kubernetes.io/name: ravendb-operator
#     app.kubernetes.io/managed-by: kustomize
#   name: ravendbcluster-sample
#   namespace: ravendb
# spec:
#   nodes:
#     - name: a
#       publicServerUrl: http://a.thegoldenplatypus.development.run:8080
#       publicServerUrlTcp: tcp://a-tcp.thegoldenplatypus.development.run:38888
#     - name: b
#       publicServerUrl: http://b.thegoldenplatypus.development.run:8080
#       publicServerUrlTcp: tcp://b-tcp.thegoldenplatypus.development.run:38888
#     - name: c
#       publicServerUrl: http://c.thegoldenplatypus.development.run:8080
#       publicServerUrlTcp: tcp://c-tcp.thegoldenplatypus.development.run:38888

#   image: ravendb/ravendb:latest
#   imagePullPolicy: IfNotPresent
#   mode: None
#   license: ''
#   domain: thegoldenplatypus.development.run
#   serverUrl: http://0.0.0.0:8080
#   serverUrlTcp: tcp://0.0.0.0:38888
#   storageSize: 5Gi
#   ingressClassName: nginx



