apiVersion: ravendb.ravendb.io/v1alpha1
kind: RavenDBCluster
metadata:
  labels:
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/managed-by: kustomize
  name: ravendbcluster-sample
  namespace: ravendb
spec:
  nodes:
    - tag: a
      publicServerUrl: https://a.thegoldenplatypus.development.run:443
      publicServerUrlTcp: tcp://a-tcp.thegoldenplatypus.development.run:443
    - tag: b
      publicServerUrl: https://b.thegoldenplatypus.development.run:443
      publicServerUrlTcp: tcp://b-tcp.thegoldenplatypus.development.run:443
    - tag: c
      publicServerUrl: https://c.thegoldenplatypus.development.run:443
      publicServerUrlTcp: tcp://c-tcp.thegoldenplatypus.development.run:443

  image: ravendb/ravendb:latest
  imagePullPolicy: IfNotPresent
  mode: None
  email: omer.ratsaby@ravendb.net
  certsSecretRef: ravendb-cert
  licenseSecretRef: ravendb-license
  domain: thegoldenplatypus.development.run
  serverUrl: https://0.0.0.0:443
  serverUrlTcp: tcp://0.0.0.0:38888
  storageSize: 5Gi
  ingressClassName: nginx

