apiVersion: ravendb.ravendb.io/v1alpha1
kind: RavenDBCluster
metadata:
  labels:
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/managed-by: kustomize
  name: ravendbcluster-sample
  namespace: ravendb
spec:
  nodes:
    - tag: a
      publicServerUrl: https://a.thegoldenplatypus-ss.development.run:443
      publicServerUrlTcp: tcp://a-tcp.thegoldenplatypus-ss.development.run:443
    - tag: b
      publicServerUrl: https://b.thegoldenplatypus-ss.development.run:443
      publicServerUrlTcp: tcp://b-tcp.thegoldenplatypus-ss.development.run:443
    - tag: c
      publicServerUrl: https://c.thegoldenplatypus-ss.development.run:443
      publicServerUrlTcp: tcp://c-tcp.thegoldenplatypus-ss.development.run:443

  image: ravendb/ravendb:latest
  imagePullPolicy: IfNotPresent
  mode: None
  email: omer.ratsaby@ravendb.net
  certsSecretRef: ravendb-cert
  licenseSecretRef: ravendb-license
  domain: thegoldenplatypus-ss.development.run

  externalAccessConfiguration:
    type: ingress-controller
    ingressControllerContext:
      ingressClassName: nginx

  storage:
      data:
        size: 10Gi
        storageClassName: local-path