apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
  name: selfsigned-issuer
  namespace: ravendb-operator-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: ravendb-operator-system
spec:
  dnsNames:
  - webhook-service.ravendb-operator-system.svc
  - webhook-service.ravendb-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
  privateKey:
    rotationPolicy: Always
