apiVersion: v1
kind: ServiceAccount
metadata:
  name: ravendb-operator-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: ravendb-operator
    control-plane: controller-manager
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: ravendb-operator
    control-plane: controller-manager
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app: ravendb-operator
    control-plane: controller-manager
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: ravendb-operator-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ravendb-operator-manager-role
  labels:
    app: ravendb-operator
    control-plane: controller-manager
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch","update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create","patch","update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["ravendb.ravendb.io"]
    resources: ["ravendbclusters"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["ravendb.ravendb.io"]
    resources: ["ravendbclusters/finalizers"]
    verbs: ["update"]
  - apiGroups: ["ravendb.ravendb.io"]
    resources: ["ravendbclusters/status"]
    verbs: ["get","patch","update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
  labels:
    app: ravendb-operator
    control-plane: controller-manager
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ravendb-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: ravendb-operator-sa
    namespace: {{ .Release.Namespace }}
