{{- $ravendbNs := .Values.ravendb.namespace | default "ravendb" }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ravendb-node
  namespace: {{ $ravendbNs }}
  labels:
    app: ravendb-node
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ravendb-node
  namespace: {{ $ravendbNs }}
  labels:
    app: ravendb-node
rules:
- apiGroups: ["ravendb.ravendb.io"]
  resources: ["ravendbclusters"]
  verbs: ["get","list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","patch","update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ravendb-node-binding
  namespace: {{ $ravendbNs }}
  labels:
    app: ravendb-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ravendb-node
subjects:
- kind: ServiceAccount
  name: ravendb-node
  namespace: {{ $ravendbNs }}
