{{- if and .Values.ravendb.enabled (eq (default "" .Values.ravendb.mode) "LetsEncrypt") }}
{{- $ns := required "ravendb.namespace is required" .Values.ravendb.namespace -}}
{{- $prefix := required "ravendb.nodeCertsSecretNamePrefix is required" .Values.ravendb.nodeCertsSecretNamePrefix -}}
{{- range $i, $tag := .Values.ravendb.nodeTags }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $prefix }}-{{ $tag | lower }}
  namespace: {{ $ns }}
type: Opaque
data:
  server.pfx: {{ required (printf "missing ravendb.nodePfx.%s (use --set-file ravendb.nodePfx.%s=...)" ($tag|lower) ($tag|lower)) (index $.Values.ravendb.nodePfx ($tag | lower)) | b64enc }}
---
{{- end }}
{{- end }}
