{{- if and .Values.provisioning (eq (default "" .Values.provisioning.mode) "None") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioning.serverCertSecretName }}
  namespace: ravendb
type: Opaque
data:
  server.pfx: {{ .Values.provisioning.serverPfx | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioning.caSecretName }}
  namespace: ravendb
type: Opaque
data:
  ca.crt: {{ .Values.provisioning.caCrt | b64enc }}
{{- end }}
