{{- $ns := default "ravendb" .Values.ravendb.namespace }}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ravendb-node-binding
  namespace: {{ $ns }}
  labels:
    {{- include "ravendb-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ravendb-node
subjects:
  - kind: ServiceAccount
    name: ravendb-node
    namespace: {{ $ns }}
