apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ravendbcluster-editor-role
  labels:
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: ["ravendb.ravendb.io"]
    resources: ["ravendbclusters"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["ravendb.ravendb.io"]
    resources: ["ravendbclusters/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ravendbcluster-viewer-role
  labels:
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: ["ravendb.ravendb.io"]
    resources: ["ravendbclusters"]
    verbs: ["get","list","watch"]
  - apiGroups: ["ravendb.ravendb.io"]
    resources: ["ravendbclusters/status"]
    verbs: ["get"]
