{{- if and .Values.provisioning .Values.provisioning.clientPfx (ne .Values.provisioning.clientPfx "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioning.adminClientCertSecretName }}
  namespace: ravendb
type: Opaque
data:
  client.pfx: {{ .Values.provisioning.clientPfx | b64enc }}
{{- end }}
