{{- if and .Values.provisioning .Values.provisioning.nodePfx (gt (len .Values.provisioning.nodePfx) 0) (eq .Values.provisioning.mode "LetsEncrypt") }}
{{- $prefix := required "provisioning.nodeCertsSecretNamePrefix is required" .Values.provisioning.nodeCertsSecretNamePrefix -}}
{{- range $i, $tag := .Values.provisioning.nodeTags }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $prefix }}-{{ $tag | lower }}
  namespace: ravendb
type: Opaque
data:
  server.pfx: {{ required (printf "missing provisioning.nodePfx.%s (use --set-file provisioning.nodePfx.%s=...)" ($tag|lower) ($tag|lower)) (index $.Values.provisioning.nodePfx ($tag | lower)) | b64enc }}
---
{{- end }}
{{- end }}
