{{- if .Values.ravendb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ravendb.clientSecretName }}
  namespace: {{ .Values.ravendb.namespace }}
type: Opaque
data:
  client.pfx: {{ .Values.ravendb.clientPfx | b64enc }}
{{- end }}
