{{- if and .Values.ravendb.enabled (eq (default "" .Values.ravendb.mode) "None") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ravendb.serverCertSecretName }}
  namespace: {{ .Values.ravendb.namespace }}
type: Opaque
data:
  server.pfx: {{ .Values.ravendb.serverPfx | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ravendb.caSecretName }}
  namespace: {{ .Values.ravendb.namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.ravendb.caCrt | b64enc }}
{{- end }}
