{{- if and .Values.provisioning (eq (default "" .Values.provisioning.mode) "LetsEncrypt") }}
{{- $prefix := required "ravendb.nodeCertsSecretNamePrefix is required" .Values.provisioning.nodeCertsSecretNamePrefix -}}
{{- range $i, $tag := .Values.provisioning.nodeTags }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $prefix }}-{{ $tag | lower }}
  namespace: ravendb
type: Opaque
data:
  server.pfx: {{ required (printf "missing ravendb.nodePfx.%s (use --set-file ravendb.nodePfx.%s=...)" ($tag|lower) ($tag|lower)) (index $.Values.provisioning.nodePfx ($tag | lower)) | b64enc }}
---
{{- end }}
{{- end }}
