apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ravendb-operator.fullname" . }}-ravendbcluster-viewer-role
  labels:
    {{- include "ravendb-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ravendb.ravendb.io
    resources:
      - ravendbclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ravendb.ravendb.io
    resources:
      - ravendbclusters/status
    verbs:
      - get
