{{- if .Values.provisioning }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioning.licenseSecretName }}
  namespace: ravendb
type: Opaque
data:
  license.json: {{ .Values.provisioning.licenseJson | b64enc }}
{{- end }}
