{{- if .Values.ravendb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ravendb.licenseSecretName }}
  namespace: {{ .Values.ravendb.namespace }}
type: Opaque
data:
  license.json: {{ .Values.ravendb.licenseJson | b64enc }}
{{- end }}
