{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ravendb-operator.serviceAccountName" . }}
  labels:
    {{- include "ravendb-operator.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
