apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ravendb-operator.fullname" . }}-serving-cert
  labels:
    {{- include "ravendb-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "ravendb-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "ravendb-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "ravendb-operator.fullname" . }}-selfsigned-issuer
  privateKey:
    rotationPolicy: Always
  secretName: webhook-server-cert
