apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "ravendb-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "ravendb-operator.fullname" . }}-serving-cert
  labels:
    {{- include "ravendb-operator.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "ravendb-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-ravendb-ravendb-io-v1-ravendbcluster
    failurePolicy: Fail
    name: vravendbcluster.kb.io
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - ravendb-operator-system
    rules:
      - apiGroups:
          - ravendb.ravendb.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ravendbclusters
    sideEffects: None
